/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type DiscordUser = {
    id: string;
    username: string;
};

export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type ListingSchema = {
    id: number;
    title: string;
    description: string | null;
    price: string | null;
    type: ListingType;
    status: ListingStatus;
    url: string;
};

export type ListingStatus = 'open' | 'pending' | 'closed';

export type ListingType = 'buy' | 'sell';

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};
