/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type DiscordUser = {
    id: string;
    username: string;
};

export type ListingSchema = {
    id: number;
    title: string;
    description: string | null;
    price: string | null;
    type: ListingType;
    status: ListingStatus;
};

export type ListingStatus = 'open' | 'pending' | 'closed';

export type ListingType = 'buy' | 'sell';
