/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type CreateListingSchema = {
    /**
     * @minLength 1
     */
    title: string;
    /**
     * @minLength 0
     */
    description: string;
    /**
     * @minLength 0
     */
    price: string;
    type: ListingType;
};

export type DiscordUser = {
    id: string;
    username: string;
    is_owner: boolean;
};

export type EditListingSchema = {
    /**
     * @minLength 1
     */
    title: string;
    /**
     * @minLength 0
     */
    description: string;
    /**
     * @minLength 0
     */
    price: string;
    status: ListingStatus;
};

export type FullListingSchema = {
    id: number;
    title: string;
    description: string;
    price: string;
    type: ListingType;
    status: ListingStatus;
    url: string;
    owner_id: string;
    issues: ListingIssueDetailsSchema[];
    images: ListingImageSchema[];
};

export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type ListingImageSchema = {
    id: number;
    width: number;
    height: number;
    url: string;
    thumbnail_url: string;
};

export type ListingIssueDetailsSchema = {
    title: string;
    description: string;
    icon: ListingIssueIcon;
    resolution_location: ListingIssueResolutionLocation;
};

export type ListingIssueIcon = 'image' | 'text' | 'dollar-sign';

export type ListingIssueResolutionLocation = 'ui' | 'discord';

export type ListingSchema = {
    id: number;
    title: string;
    description: string;
    price: string;
    type: ListingType;
    status: ListingStatus;
    url: string;
    owner_id: string;
    issues: ListingIssueDetailsSchema[];
};

export type ListingStatus = 'open' | 'pending' | 'closed';

export type ListingType = 'buy' | 'sell';

export type SearchListingsSchema = {
    statuses?: ListingStatus[] | null;
    owners?: string[] | null;
    types?: ListingType[] | null;
    has_issues?: boolean | null;
};

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};
