// Generated by ts-to-zod
import { z } from 'zod';

export const listingTypeSchema = z.union([z.literal('buy'), z.literal('sell')]);

export const discordUserSchema = z.object({
    id: z.string(),
    username: z.string(),
    is_owner: z.boolean(),
});

export const listingStatusSchema = z.union([z.literal('open'), z.literal('pending'), z.literal('closed')]);

export const validationErrorSchema = z.object({
    loc: z.array(z.union([z.string(), z.number()])),
    msg: z.string(),
    type: z.string(),
});

export const listingSchemaSchema = z.object({
    id: z.number(),
    title: z.string(),
    description: z.string().nullable(),
    price: z.string().nullable(),
    type: listingTypeSchema,
    status: listingStatusSchema,
    url: z.string(),
});

export const createListingSchemaSchema = z.object({
    title: z.string().min(1),
    description: z.string().min(0),
    price: z.string().min(0),
    type: listingTypeSchema,
});

export const editListingSchemaSchema = z.object({
    title: z.string().min(1),
    description: z.string().min(0),
    price: z.string().min(0),
    status: listingStatusSchema,
});

export const hTTPValidationErrorSchema = z.object({
    detail: z.array(validationErrorSchema).optional(),
});
