/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type CreateListingSchema = {
    /**
     * @minLength 1
     */
    title: string;
    /**
     * @minLength 0
     */
    description: string;
    /**
     * @minLength 0
     */
    price: string;
    type: ListingType;
};

export type DiscordUser = {
    id: string;
    username: string;
    is_owner: boolean;
};

export type EditListingSchema = {
    /**
     * @minLength 1
     */
    title: string;
    /**
     * @minLength 0
     */
    description: string;
    /**
     * @minLength 0
     */
    price: string;
    status: ListingStatus;
};

export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type ListingSchema = {
    id: number;
    title: string;
    description: string | null;
    price: string | null;
    type: ListingType;
    status: ListingStatus;
    url: string;
};

export type ListingStatus = 'open' | 'pending' | 'closed';

export type ListingType = 'buy' | 'sell';

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};
