name: Build Docker Image

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: earthly/actions-setup@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  version: 'latest'
            - name: Log into registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push to GitHub Packages
              run: earthly --ci --push +app
